export const videoDataDolly = [
  {
    id: 1,
    image: '/Cover (0).jpg',
    title: 'A Brief History Of Creation',
    views: '80k',
    timeAgo: '3 days',
    duration: '4:15',
    author: 'Dollie Blair',
  },
  {
    id: 2,
    image: '/Cover (1).jpg',
    title: 'Selecting The Right Hotel',
    views: '54k',
    timeAgo: '1 months',
    duration: '2:12',
    author: 'Dollie Blair',
  },
  {
    id: 3,
    image: '/Cover (2).jpg',
    title: 'Asteroids',
    views: '54k',
    timeAgo: '12 days',
    duration: '2:12',
    author: 'Dollie Blair',
  },
  {
    id: 4,
    image: '/Cover (3).jpg',
    title: 'Telescopes 101',
    views: '54k',
    timeAgo: '6 months',
    duration: '2:12',
    author: 'Dollie Blair',
  },
  {
    id: 5,
    image: '/Cover (4).jpg',
    title: 'Medical Care Is Just',
    views: '54k',
    timeAgo: '2 days',
    duration: '2:12',
    author: 'Dollie Blair',
  },
  {
    id: 6,
    image: '/Cover (5).jpg',
    title: 'Medical Care Is Just',
    views: '54k',
    timeAgo: '2 days',
    duration: '2:12',
    author: 'Dollie Blair',
  },
];

export const videoDataRecommended = [
  {
    id: 1,
    image: '/Cover (6).jpg',
    title: 'A Brief History Of Creation',
    views: '80k',
    timeAgo: '3 days',
    duration: '4:15',
    author: 'Dollie Blair',
  },
  {
    id: 2,
    image: '/Cover (7).jpg',
    title: 'Selecting The Right Hotel',
    views: '54k',
    timeAgo: '1 months',
    duration: '2:12',
    author: 'Dollie Blair',
  },
  {
    id: 3,
    image: '/Cover (8).jpg',
    title: 'Asteroids',
    views: '54k',
    timeAgo: '12 days',
    duration: '2:12',
    author: 'Dollie Blair',
  },
  {
    id: 4,
    image: '/Cover (3).jpg',
    title: 'Telescopes 101',
    views: '54k',
    timeAgo: '6 months',
    duration: '2:12',
    author: 'Dollie Blair',
  },
  {
    id: 5,
    image: '/Cover (4).jpg',
    title: 'Medical Care Is Just',
    views: '54k',
    timeAgo: '2 days',
    duration: '2:12',
    author: 'Dollie Blair',
  },
];
